#pragma once

#include <array>
#include <string_view>

namespace savor::db::events {

inline constexpr std::array<std::string_view, 76> kEventCatalogV1{ {
    "Execution.JobSetCreated.v1",
    "Execution.JobQueued.v1",
    "Execution.JobClaimed.v1",
    "Execution.JobStarted.v1",
    "Execution.JobLeaseRenewed.v1",
    "Execution.JobProgressed.v2",
    "Execution.JobCompleted.v1",
    "Execution.JobEventArchived.v1",
    "Execution.JobRestored.v1",
    "Execution.WorkflowInstanceCreated.v1",
    "Execution.WorkflowStepReady.v1",
    "Execution.WorkflowStepMaterialized.v1",
    "Execution.WorkflowStepCompleted.v1",
    "Execution.WorkflowStepFailed.v1",
    "Execution.WorkflowStepBlocked.v1",
    "Execution.WorkflowTransitionEvaluated.v1",
    "Execution.WorkflowTransitionAdvanced.v1",
    "Execution.WorkflowTransitionBlocked.v1",
    "Execution.WorkflowStepEmpty.v1",
    "Execution.WorkflowStepCoordinatorFailure.v1",
    "Execution.WorkflowStepInputRequested.v1",
    "Execution.WorkflowStepInputFragmentReady.v1",
    "Execution.WorkflowStepInputComplete.v1",
    "Execution.WorkflowInvariantViolation.v1",
    "Execution.WorkflowRemediationRepairExecuted.v1",
    "Execution.WorkflowRemediationReopened.v1",
    "Execution.WorkflowRemediationTerminalFailed.v1",
    "Execution.WorkflowInstanceCompleted.v1",
    "State.ArtifactStored.v1",
    "State.SavestateCreated.v1",
    "State.SavestateDerived.v1",
    "State.TasMovieRootCreated.v1",
    "State.TasMovieTreeCreated.v1",
    "AnalysisSpine.RunCreated.v1",
    "AnalysisSpine.StateRefRegistered.v1",
    "AnalysisSpine.LineageEdgeAdded.v1",
    "AnalysisSpine.ArtifactLinked.v1",
    "AnalysisSeedProbe.SetCreated.v1",
    "AnalysisSeedProbe.RunRequested.v1",
    "AnalysisSeedProbe.ObservationRecorded.v1",
    "AnalysisSeedProbe.EvidenceStateChanged.v1",
    "AnalysisSeedProbe.AcceptedInputFramesReplaced.v1",
    "AnalysisSeedProbe.RunStatusChanged.v1",
    "AnalysisSeedProbe.EncounterProjectionRecorded.v1",
    "AnalysisSeedProbe.RunCompleted.v1",
    "AnalysisSeedProbe.RunFailed.v1",
    "AnalysisBattle.BattleSetCreated.v1",
    "AnalysisBattle.SeedCandidateAdded.v1",
    "AnalysisBattle.TurnWaveCreated.v1",
    "AnalysisBattle.TurnJobRecorded.v1",
    "AnalysisBattle.TurnJobResultUpdated.v1",
    "AnalysisBattle.TurnWaveStatusUpdated.v1",
    "AnalysisBattle.BattleSetStatusUpdated.v1",
    "AnalysisBattle.BattleAdvancementPoolCreated.v1",
    "AnalysisBattle.BattleAdvancementDecisionRecorded.v1",
    "AnalysisBattle.ManualFollowupUpdated.v1",
    "AnalysisBattle.BattleCompletionCreated.v1",
    "AnalysisBattle.BattleCompletionCompleted.v1",
    "AnalysisBattle.BattleCompletionFailed.v1",
    "AnalysisBattle.BattleRecordingCreated.v1",
    "AnalysisBattle.BattleRecordingCompleted.v1",
    "AnalysisBattle.BattleRecordingFailed.v1",
    "AnalysisBattle.BattleReplayCreated.v1",
    "AnalysisBattle.BattleReplayCompleted.v1",
    "AnalysisBattle.BattleReplayFailed.v1",
    "Authoring.SeedProbeSpecSaved.v1",
    "Authoring.TasSpecSaved.v1",
    "Authoring.PlanSaved.v1",
    "Authoring.BattlePlanActionPresetSaved.v1",
    "Authoring.BattlePlanActionPresetRenamed.v1",
    "Authoring.WorkflowGraphSaved.v1",
    "Archive.PackageCreated.v1",
    "Archive.PackageIndexed.v1",
    "Archive.RehydrateRequested.v1",
    "Archive.RehydrateCompleted.v1",
    "Archive.RehydrateFailed.v1",
} };

inline constexpr std::array<std::string_view, 19> kWorkflowExecutionEventsV1{ {
    "Execution.WorkflowInstanceCreated.v1",
    "Execution.WorkflowStepReady.v1",
    "Execution.WorkflowStepMaterialized.v1",
    "Execution.WorkflowStepCompleted.v1",
    "Execution.WorkflowStepFailed.v1",
    "Execution.WorkflowStepBlocked.v1",
    "Execution.WorkflowTransitionEvaluated.v1",
    "Execution.WorkflowTransitionAdvanced.v1",
    "Execution.WorkflowTransitionBlocked.v1",
    "Execution.WorkflowStepEmpty.v1",
    "Execution.WorkflowStepCoordinatorFailure.v1",
    "Execution.WorkflowStepInputRequested.v1",
    "Execution.WorkflowStepInputFragmentReady.v1",
    "Execution.WorkflowStepInputComplete.v1",
    "Execution.WorkflowInvariantViolation.v1",
    "Execution.WorkflowRemediationRepairExecuted.v1",
    "Execution.WorkflowRemediationReopened.v1",
    "Execution.WorkflowRemediationTerminalFailed.v1",
    "Execution.WorkflowInstanceCompleted.v1",
} };

} // namespace savor::db::events
