#pragma once

#include <array>
#include <string_view>

namespace simcore::db::events {

inline constexpr std::array<std::string_view, 67> kEventCatalogV1{ {
    "Execution.JobSetCreated.v1",
    "Execution.JobQueued.v1",
    "Execution.JobClaimed.v1",
    "Execution.JobLeaseRenewed.v1",
    "Execution.JobProgressed.v1",
    "Execution.JobCompleted.v1",
    "Execution.JobEventArchived.v1",
    "Execution.JobRestored.v1",
    "Execution.WorkflowInstanceCreated.v1",
    "Execution.WorkflowStepReady.v1",
    "Execution.WorkflowStepMaterialized.v1",
    "Execution.WorkflowStepCompleted.v1",
    "Execution.WorkflowStepFailed.v1",
    "Execution.WorkflowStepBlocked.v1",
    "Execution.WorkflowTransitionEvaluated.v1",
    "Execution.WorkflowTransitionAdvanced.v1",
    "Execution.WorkflowTransitionBlocked.v1",
    "Execution.WorkflowStepEmpty.v1",
    "Execution.WorkflowStepCoordinatorFailure.v1",
    "Execution.WorkflowStepInputRequested.v1",
    "Execution.WorkflowStepInputFragmentReady.v1",
    "Execution.WorkflowStepInputComplete.v1",
    "Execution.WorkflowInvariantViolation.v1",
    "Execution.WorkflowRemediationRepairExecuted.v1",
    "Execution.WorkflowRemediationReopened.v1",
    "Execution.WorkflowRemediationTerminalFailed.v1",
    "Execution.WorkflowInstanceCompleted.v1",
    "State.ArtifactStored.v1",
    "State.SavestateCreated.v1",
    "State.SavestateDerived.v1",
    "State.TasVariantCreated.v1",
    "State.TasVariantProducedSavestateSet.v1",
    "AnalysisSpine.RunCreated.v1",
    "AnalysisSpine.StateRefRegistered.v1",
    "AnalysisSpine.LineageEdgeAdded.v1",
    "AnalysisSpine.ArtifactLinked.v1",
    "AnalysisSeedProbe.SetCreated.v1",
    "AnalysisSeedProbe.RunRequested.v1",
    "AnalysisSeedProbe.NeutralSeedRecorded.v1",
    "AnalysisSeedProbe.GridSeedRecorded.v1",
    "AnalysisSeedProbe.UniqueSeedRecorded.v1",
    "AnalysisSeedProbe.EncounterProjectionRecorded.v1",
    "AnalysisSeedProbe.RunCompleted.v1",
    "AnalysisBattle.BattleSetCreated.v1",
    "AnalysisBattle.SeedCandidateAdded.v1",
    "AnalysisBattle.TurnWaveCreated.v1",
    "AnalysisBattle.TurnJobRecorded.v1",
    "AnalysisBattle.SelectionPoolCreated.v1",
    "AnalysisBattle.SelectionDecisionRecorded.v1",
    "AnalysisBattle.TerminalFollowupUpdated.v1",
    "Authoring.SeedProbeSpecSaved.v1",
    "Authoring.TasSpecSaved.v1",
    "Authoring.BattleRunSpecSaved.v1",
    "Authoring.PlanSaved.v1",
    "Authoring.BattlePlanActionPresetSaved.v1",
    "Authoring.BattlePlanActionPresetRenamed.v1",
    "Authoring.PredicateSpecSaved.v1",
    "Authoring.PredicateSpecUpdated.v1",
    "Authoring.PredicateSpecDeleted.v1",
    "Authoring.SettingsSaved.v1",
    "Authoring.BattleChainSpecSaved.v1",
    "Authoring.WorkflowGraphSaved.v1",
    "Archive.PackageCreated.v1",
    "Archive.PackageIndexed.v1",
    "Archive.RehydrateRequested.v1",
    "Archive.RehydrateCompleted.v1",
    "Archive.RehydrateFailed.v1",
} };

inline constexpr std::array<std::string_view, 19> kWorkflowExecutionEventsV1{ {
    "Execution.WorkflowInstanceCreated.v1",
    "Execution.WorkflowStepReady.v1",
    "Execution.WorkflowStepMaterialized.v1",
    "Execution.WorkflowStepCompleted.v1",
    "Execution.WorkflowStepFailed.v1",
    "Execution.WorkflowStepBlocked.v1",
    "Execution.WorkflowTransitionEvaluated.v1",
    "Execution.WorkflowTransitionAdvanced.v1",
    "Execution.WorkflowTransitionBlocked.v1",
    "Execution.WorkflowStepEmpty.v1",
    "Execution.WorkflowStepCoordinatorFailure.v1",
    "Execution.WorkflowStepInputRequested.v1",
    "Execution.WorkflowStepInputFragmentReady.v1",
    "Execution.WorkflowStepInputComplete.v1",
    "Execution.WorkflowInvariantViolation.v1",
    "Execution.WorkflowRemediationRepairExecuted.v1",
    "Execution.WorkflowRemediationReopened.v1",
    "Execution.WorkflowRemediationTerminalFailed.v1",
    "Execution.WorkflowInstanceCompleted.v1",
} };

} // namespace simcore::db::events
